config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  root 'homes#top'
  get "search" => "searches#search"
  # ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags do
    get 'tweets', to: 'tweets#search'
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 通知一覧
  resources :notifications, only: :index
  # DM機能
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  # tweetが削除されるとその投稿に関連してるtagが削除される
  has_many :tag_maps, dependent: :destroy
  # throughオプションを使う場合、先にその中間テーブルとの関連付けを行う必要がある
  has_many :tags, through: :tag_maps

  has_many :tweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  attachment :image

  validates :body, presence: true, length: { maximum: 300 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(word)
    @search_tweets = Tweet.where("body LIKE?", "%#{word}%")
  end

  def save_tag(sent_tags)
    # ツイートのcreateアクションにて保存した＠tweetに紐付いているタグが存在する場合、タグの名前を配列として全て取得する
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    # 取得した@tweetの存在するタグから、送信されてきたタグを除いたタグをold_tagsとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから、現在存在するタグを除いたタグをnew_tagsとする
    new_tags = sent_tags - current_tags

    # 古いタグの削除
    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_tag
    end
  end

  def create_notification_like!(current_user)
    # すでにいいねされているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and tweet_id = ? and action = ?", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        tweet_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, tweet_comment_id)
    # 自分以外にコメントしている人全て取得し、全員に通知を送る
    temp_ids = TweetComment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, tweet_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, tweet_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, tweet_comment_id, visited_id)
    # コメントは複数回することが考えられるため、1つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      tweet_id: id,
      tweet_comment_id: tweet_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @tag_list = Tag.all
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(10)
    # where(user_id: [current_user.id, *current_user.following_ids])
  end

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
    @tweet_tags = @tweet.tags
  end

  def search
    @tag = Tag.find(params[:tag_id])                    # 参照したタグを取得
    @tweets = @tag.tweets.page(params[:page]).per(10)   # 参照したタグに紐付けられた投稿を全て表示
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    # params[:tweet][:tag_name]　formから@tweetオブジェクトを参照してタグの名前も一緒に送信するのでこの形で取得する
    # .split(nil)　送られてきた値を、スペースで区切って配列化する 配列化する理由は後でこの値をデータベースに保存する際に1つずつ繰り返し処理で取り出す必要があるため
    tag_list = params[:tweet][:tag_name].split(nil)
    if @tweet.save
      # タグの配列をデータベースに保存する処理
      @tweet.save_tag(tag_list)
      redirect_to tweets_path
    else
      render 'new'
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet)
    else
      render 'edit'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :image)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_favorites.html.erb
<% if tweet.favorited_by?(current_user) %>
  <p>
    <%= link_to tweet_favorites_path(tweet), method: :delete, remote: true do %>
      <i class="favorite-icon-up fas fa-thumbs-up"> <%= tweet.favorites.count %></i>
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to tweet_favorites_path(tweet), method: :post, remote: true do %>
      <i class="favorite-icon-down fas fa-thumbs-up"> <%= tweet.favorites.count %></i>
    <% end %>
  </p>
<% end %>

app/views/tweets/_index_search.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <h2 class="timeline"><i class="fas fa-search"></i> <%= @word %></h2>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-12">
      <div class="tweet-back mx-1 mx-lg-5">
        <div class="search-back">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr class="table-info">
                  <th></th>
                  <th class="text-nowrap">名前</th>
                  <th class="text-nowrap">タグ</th>
                  <th class="text-nowrap col-6">ツイート内容</th>
                  <th class="text-nowrap">いいね数</th>
                  <th class="text-nowrap">コメント数</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% tweets.each do |tweet| %>
                <tr>
                  <td>
                    <%= link_to user_path(tweet.user) do %>
                      <%= attachment_image_tag tweet.user, :profile_image, size: "100x100",fallback: "guest-icon.jpg", class: "effect" %><br>
                    <% end %>
                  </td>
                  <td>
                    <div class="search-td"><%= tweet.user.name %></div>
                  </td>
                  <td>
                    <% tweet.tags.each do |tag| %>
                      <%= link_to tag_tweets_path(tag_id: tag.id) do %>
                        <div class="search-td">#<%= tag.tag_name %></div>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to tweet_path(tweet) do %>
                      <%= tweet.body %>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <%= tweet.favorites.count %>
                  </td>
                  <td class="text-center">
                    <%= tweet.tweet_comments.count %>
                  </td>
                  <td class="d-flex justify-content-center text-nowrap">
                    <% if tweet.user.id != current_user.id %>
                      <%= render "users/follow_btn", user: tweet.user %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_index_tag_search.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h2 class="timeline"><i class="fas fa-search"></i> <%= @word %></h2>
    <div class="col-12">
      <div class="tweet-back mx-0 mx-lg-5 mt-5">
        <div class="search-back">
          <table class="table table-hover">
            <thead>
              <tr class="table-info">
                <th>タグ</th>
              </tr>
            </thead>
            <tbody>
              <% tags.each do |tag| %>
              <tr>
                <td>
                  <%= link_to tag_tweets_path(tag_id: tag.id) do %>
                    #<%= tag.tag_name %><br>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="new-tweet">ツイート編集</div>
  </div>
  <div class="tweet-edit mt-5">
    <div class="row justify-content-center">
      <div class="col-12">
        <%= link_to "", tweet_path(@tweet), class: "browser-back far fa-arrow-alt-circle-left", style: "text-decoration: none; color: black;" %>
      </div>
      <div class="col-12 col-lg-9">
        <%= render 'layouts/errors', obj: @tweet %>
        <div class="mt-5">
          <%= attachment_image_tag @tweet, :image, :fill, 810, 400, width: "100%", class: "tweet-image-edit", style: "border-radius: 8px;" %>
        </div>
        <%= form_with model: @tweet, local:true do |f| %>
          <div class="form-group mt-5">
            <h4 class="mt-3">ツイート内容</h4>
            <%= f.text_area :body, class: 'form-control tweet-body-edit' %>
          </div>
          <div class="form-group mt-5">
            <h4>ツイート画像</h4>
            <%= f.attachment_field :image, class: "form-control-file" %>
          </div>
          <div class="row justify-content-center">
            <div class="form-group col-5 mt-5">
              <%= f.submit 'ツイート更新', class: "btn btn-block btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h2 class="timeline"><i class="fas fa-gamepad"></i> タイムライン</h2>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-1 side"></div>
    <div class="col-10 col-xs-12">
      <div class="tweet-back">
        <div class="tweet-image">
          <% @tweets.each do |tweet| %>
            <div class="row mb-3 tweet-shadow">
              <div class="tweet-item col-2">
                <%= link_to user_path(tweet.user) do %>
                  <%= attachment_image_tag tweet.user, :profile_image, size: "100x100",fallback: "guest-icon.jpg", class: "effect" %><br>
                <% end %>
              </div>
              <div class="tweet-item col-2">
                <i class="fas fa-user"> 名前</i>
              </div>
              <div class="tweet-item col-2">
                <i class="fas fa-medal"> ランク帯</i>
              </div>
              <div class="tweet-item col-2">
                <i class="fas fa-skull"> K/D</i>
              </div>
              <div class="tweet-created_at col-4">
                <%= tweet.created_at.strftime("%Y年%m月%d日 %H:%M") %>
              </div>
              <div class="col-2"></div>
              <div class="col-2 tweet-item-sub">
                <strong><%= tweet.user.name %></strong>
              </div>
              <div class="col-2 tweet-item-sub">
                <%= tweet.user.rank %>
              </div>
              <div class="col-2 tweet-item-sub">
                <%= tweet.user.ratio %>
              </div>
              <div class="col-4 tweet-item-fc">
                <div class="tweet-item-comment">
                  <i class="far fa-comment-dots">コメント <%= tweet.tweet_comments.count %></i>
                </div>
                <div id="favorite-<%= tweet.id %>" class="tweet-item-favorite">
                  <%= render 'tweets/favorites', tweet: tweet %>
                </div>
              </div>
              <div class="col-2"></div>
              <div class="col-10">
                <%= link_to tweet_path(tweet), style: "color: black;" do %>
                  <%= tweet.body %>
                <% end %>
              </div>
              <div class="col-2"></div>
              <div class="col-10 mt-2">
                <div class="tags">
                  <% tweet.tags.each do |tag| %>
                    <%= link_to tag_tweets_path(tag_id: tag.id), style: "text-decoration: none;" do %>
                    <span class="tag-design"><i class="fas fa-tags fa-xs"></i> <%= tag.tag_name %></span>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="col-2"></div>
              <div class="col-10 mt-2">
                <%= link_to tweet_path(tweet) do %>
                  <%= attachment_image_tag tweet, :image, :fill, 628, 400, width: "100%", class: "tweet-images", style: "border-radius: 8px;" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row justify-content-center my-4"><%= paginate @tweets %></div>
      </div>
    </div>
    <div class="col-1 side">
      <span class="back">
        <a href="#">
          <i class="fas fa-chevron-circle-up"></i>
        </a>
      </span>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="new-tweet">ツイート</div>
  </div>
  <div class="tweet-edit mt-5">
    <div class="row justify-content-center">
      <div class="col-12">
        <%= link_to "", tweets_path, class: "browser-back far fa-arrow-alt-circle-left", style: "text-decoration: none; color: #444444;" %>
      </div>
      <div class="col-12 col-lg-9">
        <%= render 'layouts/errors', obj: @tweet %>
        <%= form_with model: @tweet, local:true do |f| %>
          <div class="form-group mt-5">
            <h4 class="mt-3">ツイート内容</h4>
            <%= f.text_area :body, class: 'form-control', style: "height: 150px;" %>
          </div>
          <div class="form-group mt-5">
            <h4 class="mt-3">タグ</h4>
            <div>半角スペースを入力することで複数のタグをつけることができます。</div>
            <div>例:アプデ LMG 加藤純一</div>
            <%= f.text_field :tag_name, class: "form-control" %>
          </div>
          <div class="form-group mt-5">
            <h4>ツイート画像</h4>
            <%= f.attachment_field :image, class: "form-control-file" %>
          </div>
          <div class="row justify-content-center">
            <div class="form-group col-5 mt-5">
              <%= f.submit 'ツイートする', class: "btn btn-block btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/search.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="tag-search-title"><i class="fas fa-tags fa-xs"></i> <span class="tags"><%= @tag.tag_name %></span> の投稿一覧</div>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-1"></div>
    <div class="col-10">
      <div class="tweet-back">
        <%= link_to "", tweets_path, class: "browser-back far fa-arrow-alt-circle-left", style: "text-decoration: none; color: #444444; margin-top: 4px; margin-left: 4px;" %>
        <div class="tweet-image">
          <% @tweets.each do |tweet| %>
          <div class="row mb-3 tweet-shadow">
            <div class="tweet-item col-2">
              <%= link_to user_path(tweet.user) do %>
                <%= attachment_image_tag tweet.user, :profile_image, size: "100x100",fallback: "guest-icon.jpg", class: "effect" %><br>
              <% end %>
            </div>
            <div class="tweet-item col-2">
              <i class="fas fa-user"> 名前</i>
            </div>
            <div class="tweet-item col-2">
              <i class="fas fa-medal"> ランク帯</i>
            </div>
            <div class="tweet-item col-2">
              <i class="fas fa-skull"> K/D</i>
            </div>
            <div class="tweet-created_at col-4">
              <%= tweet.created_at.strftime("%Y年%m月%d日 %H:%M") %>
            </div>
            <div class="col-2"></div>
            <div class="col-2 tweet-item-sub">
              <%= tweet.user.name %>
            </div>
            <div class="col-2 tweet-item-sub">
              <%= tweet.user.rank %>
            </div>
            <div class="col-2 tweet-item-sub">
              <%= tweet.user.ratio %>
            </div>
            <div class="col-4 tweet-item-sub">
              <% if tweet.user.id != current_user.id %>
                <div class="tweet-created_at"><%= render "users/follow_btn", user: tweet.user %></div>
              <% end %>
            </div>
              <div class="col-2"></div>
            <div class="col-10 mt-2">
              <div class="tags">
                <% tweet.tags.each do |tag| %>
                  <%= link_to tag_tweets_path(tag_id: tag.id), style: "text-decoration: none;" do %>
                  <span class="tag-design"><i class="fas fa-tags fa-xs"></i> <%= tag.tag_name %></span>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="col-2"></div>
            <div class="col-10 mt-3">
              <%= link_to tweet.body, tweet_path(tweet) %>
            </div>
          </div>
          <% end %>
        </div>
        <div class="row justify-content-center my-4"><%= paginate @tweets %></div>
      </div>
    </div>
    <div class="col-1"></div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class='container'>
  <div class='row justify-content-center'>
    <h2 class="user-edit mb-3 mb-lg-5"><%= @tweet.user.name %> 投稿詳細</h2>
    <div class="user-back col-12 col-lg-10 mx-auto">
      <div class="row">
        <div class="col-12 col-lg-12">
          <div><%= link_to "", tweets_path, class: "browser-back far fa-arrow-alt-circle-left", style: "text-decoration: none; color: #444444; margin-left: -8px;" %></div>
        </div>
        <div class="col-2 col-lg-4">
          <%= link_to user_path(@tweet.user) do %>
            <%= attachment_image_tag @tweet.user, :profile_image, size: "200x200",fallback: "guest-icon.jpg", class: "effect" %>
          <% end %>
        </div>
        <div class="col-5 col-lg-3 mt-2 mt-lg-5">
          <%= link_to user_followings_path(@tweet.user) do %>
            <span class="tags follow-font-color">フォロー中 <%= @tweet.user.followings.count %></span><br>
          <% end %>
          <div class="user-name mt-2 mt-lg-5">
            <%= @tweet.user.name %>
          </div>
        </div>
        <div class="col-5 col-lg-3 mt-2 mt-lg-5">
          <%= link_to user_followers_path(@tweet.user) do %>
            <span class="tags follow-font-color">フォロワー <%= @tweet.user.followers.count %></span><br>
          <% end %>
          <div class="mt-3 mt-lg-5">
            <% if @tweet.user.id != current_user.id %>
              <%= render "users/follow_btn", user: @tweet.user %>
            <% end %>
          </div>
        </div>
        <div class="col-11 col-lg-12 flame">
          <span class="flame-title tags">
            紹介文
          </span>
          <div class="profile">
            <% if @tweet.user.profile != nil %>
              <%= user_text(@tweet.user.profile) %>
            <% else %>
              よろしくお願いします。
            <% end %>
          </div>
        </div>
        <div class="col-5 col-lg-3 flame-sub mt-1">
          <span class="flame-title tags">
            ランク帯
          </span>
          <div class="text-center">
            <%= @tweet.user.rank %>
          </div>
        </div>
        <div class="col-5 col-lg-3 mt-1 flame-sub">
          <span class="flame-title tags">
            K/D
          </span>
          <div class="text-center">
            <% if @tweet.user.ratio != nil %>
              <%= @tweet.user.ratio %>
            <% else %>
              未登録
            <% end %>
          </div>
        </div>
        <hr width="100%">
        <div class="col-12 col-lg-12 tweet-delete">
          <% if @tweet.user == current_user %>
            <%= link_to edit_tweet_path(@tweet), style: "color: green; text-decoration: none;" do %>
              ツイート編集<i class="far fa-edit"></i>
            <% end %>
             <strong> / </strong>
            <%= link_to tweet_path(@tweet), style: "color: red; text-decoration: none;", method: :delete, data: { confirm: '本当に消しますか？' } do %>
              ツイート削除 <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
        <div class="tweet-item col-2 text-center">
          <%= link_to user_path(@tweet.user) do %>
            <%= attachment_image_tag @tweet.user, :profile_image, size: "100x100",fallback: "guest-icon.jpg", class: "effect" %><br>
          <% end %>
        </div>
        <div class="tweet-item-name col-2">
          <i class="fas fa-user"> 名前</i>
        </div>
        <div class="tweet-item col-2">
          <i class="fas fa-medal"> ランク帯</i>
        </div>
        <div class="tweet-item col-2">
          <i class="fas fa-skull"> K/D</i>
        </div>
        <div class="tweet-show-created_at col-4">
          <%= @tweet.created_at.strftime("%Y年%m月%d日 %H:%M") %>
        </div>
        <div class="col-2"></div>
        <div class="col-2 tweet-item-sub">
          <%= @tweet.user.name %>
        </div>
        <div class="col-2 tweet-item-sub">
          <%= @tweet.user.rank %>
        </div>
        <div class="col-2 tweet-item-sub">
          <% if @tweet.user.ratio != nil %>
            <%= @tweet.user.ratio %>
          <% else %>
            未登録
          <% end %>
        </div>
        <div class="tweet-show-created_at col-4 col-lg-4">
          <i class="far fa-comment-dots">
            コメント <%= @tweet.tweet_comments.count %>
          </i>
          <div id="favorite-<%= @tweet.id %>" class="tweet-item-favorite mt-2">
            <%= render 'tweets/favorites', tweet: @tweet %>
          </div>
        </div>
        <div class="col-2"></div>
        <div class="col-10">
          <%= user_text(@tweet.body) %>
        </div>
        <div class="col-2"></div>
        <div class="col-10 mt-2">
          <div class="tags">
            <% @tweet.tags.each do |tag| %>
              <%= link_to tag_tweets_path(tag_id: tag.id), style: "text-decoration: none;" do %>
              <span class="tag-design"><i class="fas fa-tags fa-xs"></i> <%= tag.tag_name %></span>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-2"></div>
        <div class="col-10 mt-2">
            <%= attachment_image_tag @tweet, :image, :fill, 740, 400, width: "100%", class: "tweet-images", style: "border-radius: 8px;" %>
        </div>
        <div class="col-2"></div>
        <div class="col-10 mt-3 tags">
          <i class="far fa-comments">コメント欄</i>
        </div>
        <div class="col-2"></div>
        <div id="target_comments" class="col-10 mt-3">
          <%= render 'tweet_comments/index', tweet: @tweet %>
        </div>
        <div class="col-2"></div>
        <div class=" col-10 mt-3">
          <%= form_with(model:[@tweet, @tweet_comment], remote: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに！", class: "form-control" %>
            <div class="mt-2">
              <div class="row justify-content-end">
              <%= f.submit "送信する", class: "btn btn-outline-primary mr-lg-3 mr-3" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>