config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  root 'homes#top'
  get "search" => "searches#search"
  # ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags do
    get 'tweets', to: 'tweets#search'
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 通知一覧
  resources :notifications, only: :index
  # DM機能
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  attachment :profile_image, destroy: false
  enum rank: { 非公開: 0, ブロンズ: 1, シルバー: 2, ゴールド: 3, プラチナ: 4, ダイヤ: 5, マスター: 6, プレデター: 7 }

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 自分からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  # 相手からの通知

  validates :name, presence: true, length: { maximum: 30, munimum: 2 }, uniqueness: true
  validates :profile, length: { maximum: 500 }

  def self.looks(word)
    @search_users = User.where("name LIKE?", "%#{word}%")
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
    end
  end

  # relationships_controllerで使うメソッド
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローボタン表示の際の条件分岐にて使用
  def following?(user)
    followings.include?(user)
  end

  def create_notification_follow!(current_user)
    # すでにフォローされているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    # フォローされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: [:update, :destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新･削除できません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to tweets_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order("created_at DESC").page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :profile, :ratio, :rank)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_text(text)
    return if text.blank?

    raw(email2a(url2a(nl2br(sanitize(text).to_s))))
  end
  # 改行文字をbrタグに置換
  def nl2br(text)
    text.gsub(/\R/) { %Q{<br>} }
  end
  # URLをaタグに置換
  def url2a(text)
    text.gsub(URI.regexp(%w[http https])) { %Q{<a href="#{$&}" target="_blank">#{$&}</a>} }
  end
  # メールアドレスをaタグに置換
  def email2a(text)
    text.gsub(/[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i) { %Q{<a href="mailto:#{$&}">#{$&}</a>} }
  end
end

app/views/users/_follow_btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "follow-btn-r btn btn-primary" %>
<% else %>
  <%= link_to "+フォローする", user_relationships_path(user.id), method: :post, class: "follow-btn-r btn btn-outline-primary" %>
<% end %>

app/views/users/_index_search.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <h2 class="timeline"><i class="fas fa-search"></i> <%= @word %></h2>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-12">
      <div class="tweet-back mx-1 mx-lg-5">
        <div class="search-back">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr class="table-info">
                  <th class="col-1"></th>
                  <th class="text-nowrap col-1 col-lg-1">名前</th>
                  <th class="text-nowrap col-2 col-lg-1">ランク帯</th>
                  <th class="text-nowrap col-2 col-lg-1">キルレ</th>
                  <th class="text-nowrap col-4 col-lg-6">紹介文</th>
                  <th class="col-2 col-lg-2"></th>
                </tr>
              </thead>
              <tbody>
                <% users.each do |user| %>
                <tr>
                  <td>
                    <%= link_to user_path(user) do %>
                      <%= attachment_image_tag user, :profile_image, size: "100x100",fallback: "guest-icon.jpg", class: "effect-search-index" %><br>
                    <% end %>
                  </td>
                  <td>
                    <div class="search-td"><%= user.name %></div>
                  </td>
                  <td>
                    <div class="search-td"><%= user.rank %></div>
                  </td>
                  <td>
                    <% if user.ratio != nil %>
                      <div class="search-td"><%= user.ratio %></div>
                    <% else %>
                      <div class="search-td">未登録</div>
                    <% end %>
                  </td>
                  <td>
                    <div class="search-td"><%= user.profile %></div>
                  </td>
                  <td class="d-flex justify-content-center text-nowrap">
                    <% if user.id != current_user.id %>
                      <%= render "users/follow_btn", user: user %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="new-tweet">プロフィール編集</div>
  </div>
  <div class="tweet-edit mt-5">
    <div class="row justify-content-center">
      <div class="col-12">
        <%= link_to "", user_path(@user), class: "browser-back far fa-arrow-alt-circle-left", style: "text-decoration: none; color: black;" %>
      </div>
      <div class="col-12 col-lg-9">
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model:@user, local:true do |f| %>
          <%= attachment_image_tag @user, :profile_image, size: "200x200",fallback: "guest-icon.jpg", class: "effect-user-show" %>
        <div class="form-group mt-4">
          <%= f.label 'ランク帯', class: "mb-1 tags" %>
          <%= f.select :rank, User.ranks.keys, class: "mb-1" %>
        </div>
        <div class="form-group">
          <%= f.label :ratio, "K/D", class: "mb-1 mr-3 tags" %>
          <%= f.text_field :ratio, class: 'form-control' %>
        </div>
        <div class="form-group mt-3">
          <%= f.label '名前', class: "tags" %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label '紹介文', class: "tags" %>
          <%= f.text_area :profile, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'プロフィール画像', class: "tags" %>
          <%= f.attachment_field :profile_image, class: 'form-control-file' %>
        </div>
        <div class="row justify-content-center">
          <div class="form-group col-5 mt-5">
            <%= f.submit "保存", class: 'btn btn-block btn-outline-info' %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row justify-content-center'>
    <div class="user-show"><%= @user.name %></div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-1 side"></div>
    <div class="user-back col-12 col-lg-10 mt-lg-4">
      <div class="row">
        <div class="col-3">
          <%= link_to "", tweets_path, class: "browser-back far fa-arrow-alt-circle-left", style: "text-decoration: none; color: #444444; margin-left: -8px; margin-top: -2px;" %>
        </div>
        <div class="col-9 tweet-created_at">
          <% if @user.id == current_user.id %>
            <%= link_to edit_user_path(@user) do %>
              <i class="fas fa-user-edit user-edit-icon"><span class="tags">編集</span></i>
            <% end %>
          <% end %>
        </div>
        <div class="col-2 col-lg-4">
          <%= attachment_image_tag @user, :profile_image, size: "200x200",fallback: "guest-icon.jpg", class: "effect" %>
        </div>
        <div class="col-5 col-lg-3 mt-2 mt-lg-5">
          <%= link_to user_followings_path(@user) do %>
            <span class="tags follow-font-color">フォロー中 <%= @user.followings.count %></span><br>
          <% end %>
          <div class="user-name mt-2 mt-lg-5">
            <%= @user.name %>
          </div>
        </div>
        <div class="col-5 col-lg-3 mt-2 mt-lg-5">
          <%= link_to user_followers_path(@user) do %>
            <span class="tags follow-font-color">フォロワー <%= @user.followers.count %></span><br>
          <% end %>
          <div class="mt-3 mt-lg-5">
            <% if @user.id != current_user.id %>
              <%= render "users/follow_btn", user: @user %>
            <% end %>
          </div>
        </div>
        <div class="col-2 mt-2 mt-lg-5">
          <% if current_user != @user %>
            <i class="far fa-envelope"></i> <%= link_to 'DMする', chat_path(@user.id) %>
          <% end %>
        </div>
        <div class="col-11 col-lg-12 flame">
          <span class="flame-title tags">
            紹介文
          </span>
          <div class="profile">
            <% if @user.profile != nil %>
              <%= user_text(@user.profile) %>
            <% else %>
              よろしくお願いします。
            <% end %>
          </div>
        </div>
        <div class="col-5 col-lg-3 flame-sub mt-1">
          <span class="flame-title tags">
            ランク帯
          </span>
          <div class="text-center">
            <%= @user.rank %>
          </div>
        </div>
        <div class="col-5 col-lg-3 flame-sub mt-1">
          <span class="flame-title tags">
            K/D
          </span>
          <div class="text-center">
            <% if @user.ratio != nil %>
              <%= @user.ratio %>
            <% else %>
              未登録
            <% end %>
          </div>
        </div>
        <h3 class="col-12 mt-3"><span class="tags ml-2">ツイート</span></h3>
          <% @tweets.each do |tweet| %>
            <div class="col-2 col-lg-2 mt-lg-4 tweet-item text-center">
              <%= attachment_image_tag tweet.user, :profile_image, size: "60x60",fallback: "guest-icon.jpg", class:"effect" %>
            </div>
            <div class="col-5 col-lg-5 mt-lg-4">
              <%= tweet.user.name %>
            </div>
            <div class="col-5 col-lg-5 mt-lg-4 tweet-created_at">
              <%= tweet.created_at.strftime("%Y年%m月%d日 %H:%M") %>
            </div>
            <div class="col-2 col-lg-2"></div>
            <div class="col-10 col-lg-10">
              <%= link_to tweet_path(tweet),style: "color: black;" do %>
                <%= tweet.body %>
              <% end %>
            </div>
            <div class="col-2 col-lg-2"></div>
            <div class="col-10 col-lg-10 mt-2">
              <div class="tags">
                <% tweet.tags.each do |tag| %>
                  <%= link_to tag_tweets_path(tag_id: tag.id), style: "text-decoration: none;" do %>
                  <span class="tag-design"><i class="fas fa-tags fa-xs"></i> <%= tag.tag_name %></span>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="col-2 col-lg-2"></div>
            <div class="col-10 col-lg-10 mt-2">
              <%= link_to tweet_path(tweet) do %>
                <%= attachment_image_tag tweet, :image, size: "610x400", class: "user-show-images", style: "border-radius: 8px;" %>
              <% end %>
            </div>
            <hr width="100%">
          <% end %>
          </div>
          <div class="row justify-content-center my-4"><%= paginate @tweets %></div>
        </div>
        <div class="col-1 side-user-show">
          <span class="back">
            <a href="#">
              <i class="fas fa-chevron-circle-up fa-2x"></i>
            </a>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>