config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  root 'homes#top'
  get "search" => "searches#search"
  # ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags do
    get 'tweets', to: 'tweets#search'
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 通知一覧
  resources :notifications, only: :index
  # DM機能
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  has_many :notifications, dependent: :destroy

  validates :comment, presence: true
end

app/controllers/tweet_comments_controller.rb
class TweetCommentsController < ApplicationController
  # コメント作成アクション
  def create
    @tweet = Tweet.find(params[:tweet_id])
    @tweet_comment = current_user.tweet_comments.new(tweet_comment_params)
    @tweet_comment.tweet_id = @tweet.id
    @tweet_comment.save
    @tweet.create_notification_comment!(current_user, @tweet_comment.id)
  end
  # コメント削除アクション
  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @tweet_comment_id = params[:id]
    TweetComment.find_by(id: params[:id], tweet_id: params[:tweet_id]).destroy
  end

  private

  def tweet_comment_params
    params.require(:tweet_comment).permit(:comment)
  end
end

app/helpers/tweet_comments_helper.rb
module TweetCommentsHelper
end

app/views/tweet_comments/_index.html.erb
<div class="row">
  <% @tweet.tweet_comments.each do |tweet_comment| %>
    <div class="comment-image col-3 col-lg-1">
      <%= link_to user_path(tweet_comment.user) do %>
        <%= attachment_image_tag tweet_comment.user, :profile_image, size: "50x50",fallback: "guest-icon.jpg", class: "effect" %>
      <% end %>
    </div>
    <div class="col-9 col-lg-11 tweet-show-comments">
      <%= tweet_comment.user.name %>
      <span class="ml-3"><%= tweet_comment.created_at.strftime("%Y年%m月%d日 %H:%M") %></span>
      <% if tweet_comment.user == current_user %>
        <span class="ml-4">
          <%= link_to "", tweet_tweet_comment_path(tweet_comment.tweet_id, tweet_comment.id), class: "fas fa-trash-alt", style: "color: red; font-size: 17px;", method: :delete, data: { confirm: '本当にコメントを消しますか？' }, remote: true %>
        </span>
      <% end %>
    </div>
    <div class="col-3 col-lg-1"></div>
    <div id="comment<%= tweet_comment.id %>" class="col-9 col-lg-11 mb-4 balloon-index">
      <div class="balloon"><%= tweet_comment.comment %></div>
    </div>
  <% end %>
</div>

app/views/tweet_comments/create.js.erb
$("#comments-count").html("コメント数:<%= @tweet.tweet_comments.count %>");
$("#target_comments").html("<%= j(render 'tweet_comments/index', tweet: @tweet ) %>");
$("#tweet_comment_comment").val('');

app/views/tweet_comments/destroy.js.erb
$("#comments-count").html("コメント数:<%= @tweet.tweet_comments.count %>");
$("#target_comments").html("<%= j(render 'tweet_comments/index', tweet: @tweet ) %>");
$("#tweet_comment_comment").val('');