config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  root 'homes#top'
  get "search" => "searches#search"
  # ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags do
    get 'tweets', to: 'tweets#search'
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 通知一覧
  resources :notifications, only: :index
  # DM機能
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h4 class="text-center"><%= pluralize(obj.errors.count, "箇所") %> のエラーによって保存できませんでした。</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li class="text-center"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <div class="text-center"><%= msg %></div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <% if user_signed_in? %>
      <div class="container justify-content-center">
        <div id="sp-menu">
          <ul>
            <li>
              <i class="fas fa-user-circle"></i> <%= link_to "マイページ", user_path(current_user.id), style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
            </li>
            <li>
              <i class="fas fa-pen"></i> <%= link_to "新規投稿", new_tweet_path, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
            </li>
            <li>
              <i class="fas fa-gamepad"></i> <%= link_to "タイムライン", tweets_path, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
            </li>
            <li>
              <% if unchecked_notifications.any? %>
                <span class="fa-stack">
                  <i id="bell-icon" class="fas fa-bell n-bell fa-stack-2x"></i>
                  <i id="bell-icon" class="fas fa-circle n-circle fa-stack-1x"></i>
                </span>
                <%= link_to "お知らせ", notifications_path, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
              <% else %>
                <i class="fas fa-bell"></i> <%= link_to "お知らせ", notifications_path, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
              <% end %>
            </li>
            <li>
              <i class="fas fa-sign-out-alt"></i> <%= link_to "ログアウト", destroy_user_session_path, method: :delete, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
            </li>
          </ul>
        </div>
        <div id="hm-icon">
          <a class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
        <div>
          <%= link_to root_path, data: {"turbolinks" => false} do %>
            <img id="logo" src="<%= asset_path('logo.png') %>" alt="APETTER">
          <% end %>
        </div>
        <div id="search-wrap" class="d-flex justify-content-end">
          <%= render "layouts/search" %>
        </div>
      </div>
    <% else %>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
      <div id="sp-menu">
        <ul>
          <li>
            <i class="fas fa-sign-in-alt"></i><%= link_to "ログイン", new_user_session_path, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
          </li>
          <li>
            <i class="fas fa-user-check"></i><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
          </li>
          <li>
            <i class="fas fa-user-plus"></i><%= link_to "新規登録", new_user_registration_path, style: "text-decoration: none; color: black; font-family: 'DotGothic16', sans-serif;", data: {"turbolinks" => false} %>
          </li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, class: "form-inline", local: true, method: :get do |f| %>
      <%= f.select :range, options_for_select([['ユーザー'], ['ツイート'], ['タグ']]), {}, {class: "select-tag"} %>
      <%= f.text_field :word, id: "search-text",  placeholder: "キーワードを入力" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APETTER</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/e75ffa34a6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>